apiVersion: v1
kind: Service
metadata:
  name: pythondeploy
  namespace: pythonapp
spec:
  type: LoadBalancer
  selector:
    app: pythondeploy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000